### ISSUE TITLE
Feature : Login 

### ISSUE THREAD

**Issue by fresher-batch-2021** [fresher-batch-2021/movieticketapp-ui#10]
#### BUG

* Remember me not working

**Comment by fresher-batch-2021** [comment]
* Buttons are not consistent.

**Comment by fresher-batch-2021** [comment]
Remove alerts

**Comment by fresher-batch-2021** [comment]
Error message need to be changed - Invalid Login Credentials

**Comment by fresher-batch-2021** [comment]
After login, it should display loggedin user name.

**Comment by fresher-batch-2021** [comment]
![image](https://user-images.githubusercontent.com/88075923/131982215-9dff95ce-d60e-474c-bf0f-868a10a339f3.png)

**Comment by hariharansa** [comment]
> #### BUG
> * Remember me not working

**Comment by hariharansa** [comment]
> > #### BUG
> > 
> > * Remember me not working

fixed

**Comment by hariharansa** [comment]
> Remove alerts

fixed

**Comment by hariharansa** [comment]
fixed

**Comment by hariharansa** [comment]
> * Buttons are not consistent.

fixed

**Comment by hariharansa** [comment]
> Error message need to be changed - Invalid Login Credentials

fixed
