### ISSUE TITLE
Feature - List Movies

### ISSUE THREAD

**Issue by fresher-batch-2021** [fresher-batch-2021/movieticketapp-ui#11]
UI Bug:

* Filter languages are static.
*

**Comment by fresher-batch-2021** [comment]
* BUG - Filter should have reset button.
![image](https://user-images.githubusercontent.com/88075923/131984281-579de4ea-e004-4fcd-b7a0-e5961b9ca8ae.png)

**Comment by fresher-batch-2021** [comment]
* Images are not aligned properly

**Comment by hariharansa** [comment]
> * Images are not aligned properly

fixed

**Comment by hariharansa** [comment]
BUG - Filter should have reset button.

Fixed
