### ISSUE TITLE
Feature : Booking Page

### ISSUE THREAD

**Issue by fresher-batch-2021** [fresher-batch-2021/movieticketapp-ui#12]
# BUG
* Page title is missing

**Comment by fresher-batch-2021** [comment]
#### BUG
* User is able to book past show timings ( e.g: at 11 am , user is able to book 10:30 am show).
* User is able to book tickets  with negative no of tickets.

**Comment by fresher-batch-2021** [comment]
![image](https://user-images.githubusercontent.com/88075923/131987462-9438786f-c2c8-4904-8057-684f290f6aba.png)

**Comment by hariharansa** [comment]
> # BUG
> * Page title is missing

fixed

**Comment by hariharansa** [comment]
User is able to book tickets with negative no of tickets.

fixed
