### ISSUE TITLE
Feature : User Registration 

### ISSUE THREAD

**Issue by fresher-batch-2021** [fresher-batch-2021/movieticketapp-ui#9]
#### UI Improvement

* Text color not easy to read
* Label - password to "Password" , "confirm Password"
* Remember Me  - by default checked [ static ]

#### BUG
* Link is not working - Terms and Conditions

**Comment by fresher-batch-2021** [comment]
#### BUG
* Confirm Password :  Password is visible

**Comment by fresher-batch-2021** [comment]
Data should be retained if any field data is invalid.

**Comment by fresher-batch-2021** [comment]
Increase Error message timings.

**Comment by fresher-batch-2021** [comment]
![image](https://user-images.githubusercontent.com/88075923/131981818-836085d8-8d53-4874-90c0-e10a74dc7ca7.png)

**Comment by hariharansa** [comment]
> #### UI Improvement
> * Text color not easy to read
> * Label - password to "Password" , "confirm Password"
> * Remember Me  - by default checked [ static ]
> 
> #### BUG
> * Link is not working - Terms and Conditions

fixed

**Comment by hariharansa** [comment]
> #### BUG
> * Confirm Password :  Password is visible

fixed

**Comment by hariharansa** [comment]
> Data should be retained if any field data is invalid.

fixed

**Comment by hariharansa** [comment]
> Increase Error message timings.

fixed

**Comment by hariharansa** [comment]
fixed
